name: 'Spirit Ink | Soulful Stationery + Mindful Musings'
favicon: null
layout_spectrum: 0.9323243305552751
typography_spectrum: 0.74047
title: 'Spirit Ink | Soulful Stationery + Mindful Musings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1d1b'
    - '#f5cacc'
    - '#41413f'
    - '#6d6d6d'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
