name: Spirit Ink
favicon: null
layout_spectrum: 0.9323243305552751
typography_spectrum: 0.74047
title: 'Spirit Ink | Soulful Stationery + Mindful Musings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1d1b'
    - '#f5cacc'
    - '#41413f'
    - '#6d6d6d'
  brandStrength: 0.48424045485444367
  lightness: 0.5624135418329388
  saturation: 0.024570046458393335
  rhythmicContrast: 0.0632199498359114
purpose: []
